spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:kbpack}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
  session:
    store-type: jdbc
    timeout: 12h
  flyway:
    enabled: true

server:
  servlet:
    session:
      cookie:
        secure: ${COOKIE_SECURE:true}

logging:
  level:
    root: INFO
    com.kbpack: INFO
